// Webpack configuration generated by webpacker-cli.  This file is yours to edit.
//
// Conventions (identical to Rails' Webpacker):
//   * every file in <source_path>/<source_entry_path> is an entry point
//   * output goes to <public_root_path>/<public_output_path>
//   * a manifest.json mapping "application.js" => "/packs/application-<hash>.js"
//     is written next to the output
const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')
const { WebpackAssetsManifest } = require('webpack-assets-manifest')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin')

const root = path.resolve(__dirname, '..', '..')
const envName = process.env.WEBPACKER_ENV || process.env.NODE_ENV || 'development'
const isProduction = envName === 'production'

const settings = yaml.load(fs.readFileSync(path.join(root, 'config', 'webpacker.yml'), 'utf8'))
const cfg = Object.assign({}, settings.default, settings[envName])

const sourcePath = path.resolve(root, cfg.source_path)
const entryPath = path.join(sourcePath, cfg.source_entry_path)
const outputPath = path.resolve(root, cfg.public_root_path, cfg.public_output_path)
const publicPath = `/${cfg.public_output_path.replace(/^\/+|\/+$/g, '')}/`

const entry = {}
const collect = (dir, prefix) => {
  if (!fs.existsSync(dir)) return
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    if (item.isDirectory()) {
      collect(path.join(dir, item.name), `${prefix}${item.name}/`)
    } else if (/\.(m?js|jsx|ts|tsx|css)$/.test(item.name)) {
      entry[prefix + item.name.replace(/\.[^.]+$/, '')] = path.join(dir, item.name)
    }
  }
}
collect(entryPath, '')

const hash = isProduction ? '-[contenthash]' : ''

module.exports = {
  mode: isProduction ? 'production' : 'development',
  devtool: isProduction ? 'source-map' : 'cheap-module-source-map',
  context: root,
  entry,
  output: {
    path: outputPath,
    publicPath,
    filename: `[name]${hash}.js`,
    chunkFilename: `[name]${hash}.chunk.js`,
    assetModuleFilename: `media/[name]${hash}[ext]`,
    clean: true
  },
  cache: {
    type: 'filesystem',
    cacheDirectory: path.resolve(root, cfg.cache_path),
    buildDependencies: { config: [__filename] }
  },
  module: {
    rules: [
      {
        test: /\.(js|mjs)$/,
        exclude: /node_modules/,
        use: { loader: 'babel-loader', options: { presets: [['@babel/preset-env', { targets: 'defaults' }]] } }
      },
      { test: /\.css$/, use: [MiniCssExtractPlugin.loader, 'css-loader'] },
      { test: /\.(png|jpe?g|gif|svg|webp|avif|ico|woff2?|eot|ttf|otf)$/i, type: 'asset/resource' }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({ filename: `[name]${hash}.css`, chunkFilename: `[name]${hash}.chunk.css` }),
    new WebpackAssetsManifest({ output: 'manifest.json', publicPath: true, writeToDisk: true })
  ],
  optimization: {
    minimizer: ['...', new CssMinimizerPlugin()]
  },
  resolve: {
    extensions: cfg.extensions,
    modules: [sourcePath, 'node_modules']
  },
  performance: { hints: false }
}
